<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHOqJQx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHOqJQx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHOqJQx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHOqJQx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHOqJQx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHOqJQx',
    'container.build_id' => '9aafdf25',
    'container.build_time' => 1680596946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHOqJQx');
