<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXI6CZla\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXI6CZla/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXI6CZla.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXI6CZla\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXI6CZla\App_KernelDevDebugContainer([
    'container.build_hash' => 'XI6CZla',
    'container.build_id' => '71eebe9e',
    'container.build_time' => 1680600110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXI6CZla');
