<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5KTM98\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5KTM98/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG5KTM98.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG5KTM98\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG5KTM98\App_KernelDevDebugContainer([
    'container.build_hash' => 'G5KTM98',
    'container.build_id' => 'd93bca5a',
    'container.build_time' => 1680880787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5KTM98');
